## NUMPY BASIS

In [1]:
import numpy as np

In [2]:
# absolute func

a = np.absolute(-5)
print(a)

5


In [6]:
# 1D list 

arr1d = np.array([1,2,3,4])
print(arr1d)
print(np.shape(arr1d))

[1 2 3 4]
(4,)


In [7]:
# 2D list

arr2d = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2d)
print(np.shape(arr2d))

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [12]:
# dot product 

matrix = np.dot(arr2d,arr2d.T)
print(matrix)
print(np.shape(matrix))

[[ 30  70]
 [ 70 174]]
(2, 2)


In [15]:
# random integers b/w given range
# syntax : np.random.randint( low , high , length)  
# low inclusive , high exclusive  [ )

r_int = np.random.randint(10,40,10)
print(r_int)

[34 36 34 25 38 37 35 29 18 15]


In [16]:
# also we can make 2D matrix

r_int2d = np.random.randint(10,40,(5,5))
print(r_int2d)


[[10 18 28 11 12]
 [32 35 14 38 32]
 [38 26 30 38 10]
 [31 19 39 35 36]
 [38 37 31 16 22]]


In [20]:
# to print max and min values

print("MAX : %d "%r_int2d.max())
print("MIN : %d "%r_int2d.min())

MAX : 39 
MIN : 10 


In [25]:
# min argument in list i.e.. returns index of min arg

l = [1,2,3,-3,4,-1,0,8]
print(np.argmin(l))
print(np.argmax(l))

3
7


In [26]:
# to print only unique elements by np.unique(<array name>)

arr = np.array([1,2,3,1,2,3,6,7,8,5,6])
print(np.unique(arr))

[1 2 3 5 6 7 8]


In [34]:
print(np.unique(arr,return_counts=True))

print(np.unique(arr,return_inverse=True))

(array([1, 2, 3, 5, 6, 7, 8]), array([2, 2, 2, 1, 2, 1, 1]))
(array([1, 2, 3, 5, 6, 7, 8]), array([0, 1, 2, 0, 1, 2, 4, 5, 6, 3, 4]))


In [35]:
print(r_int2d)

[[10 18 28 11 12]
 [32 35 14 38 32]
 [38 26 30 38 10]
 [31 19 39 35 36]
 [38 37 31 16 22]]


In [55]:
# slicing of an array

temp = r_int2d[2:4,1:4]
print(temp)

[[26 30 38]
 [19 39 35]]


In [56]:
# print 0,4

print(r_int2d[0][4])

12
